# -*- coding: utf-8 -*-
"""Hugging Face Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VroD-UbSRUqZgt8KnvEABzTTv45s7XdK
"""

!pip -q install transformers datasets sentence-transformers scikit-learn pandas numpy

import os
import re
import json
import random
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

from datasets import Dataset
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

BASE_PATH = Path("/content/enterprise_hf_project")
DATA_PATH = BASE_PATH / "data"
OUTPUT_PATH = BASE_PATH / "output"
CHUNK_PATH = BASE_PATH / "chunks"

for path in [BASE_PATH, DATA_PATH, OUTPUT_PATH, CHUNK_PATH]:
    path.mkdir(parents=True, exist_ok=True)

print("Project folders created successfully")

random.seed(42)

document_types = [
    "Supplier Issue Report",
    "Maintenance Log",
    "Quality Incident",
    "Finance Memo",
    "Engineering Change Notice"
]

suppliers = ["Bosch", "Siemens", "Denso", "Magna", "Valeo"]
plants = ["PLT100", "PLT200", "PLT300"]
equipment_ids = ["EQP1001", "EQP1002", "EQP1003", "EQP2001", "EQP2002"]
company_codes = ["C001", "C002", "C003"]
issues = [
    "sensor failure causing unexpected downtime",
    "voltage fluctuation impacting assembly line stability",
    "invoice mismatch for replacement material",
    "quality defect identified during inspection",
    "maintenance delay due to unavailable spare parts",
    "temperature alarm triggered in production unit",
    "supplier delivery issue impacting scheduled repairs",
    "equipment shutdown linked to recurring controller fault"
]

documents = []

for i in range(1, 51):
    supplier = random.choice(suppliers)
    plant = random.choice(plants)
    equipment = random.choice(equipment_ids)
    company = random.choice(company_codes)
    doc_type = random.choice(document_types)
    issue = random.choice(issues)
    amount = random.randint(1000, 25000)
    date = f"2024-{random.randint(1,12):02d}-{random.randint(1,28):02d}"
    common_key = f"{plant}_{equipment}"

    text = (
        f"{doc_type} for supplier {supplier} at plant {plant}. "
        f"Equipment {equipment} reported {issue}. "
        f"Document date is {date}. "
        f"Invoice amount recorded was {amount} USD. "
        f"Company code {company}. "
        f"Common business key {common_key}. "
        f"This document supports manufacturing operations, supplier review, "
        f"issue tracking, finance review, and engineering analysis."
    )

    documents.append({
        "document_id": f"DOC{i:03d}",
        "document_type": doc_type,
        "company_code": company,
        "plant_code": plant,
        "supplier_name": supplier,
        "equipment_id": equipment,
        "document_date": date,
        "invoice_amount": amount,
        "common_business_key": common_key,
        "document_text": text
    })

documents_df = pd.DataFrame(documents)
documents_df.to_csv(DATA_PATH / "enterprise_documents.csv", index=False)
documents_df.head()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s\-_\.]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

documents_df["normalized_text"] = documents_df["document_text"].apply(clean_text)
documents_df.head()

hf_dataset = Dataset.from_pandas(
    documents_df[
        [
            "document_id",
            "document_type",
            "company_code",
            "plant_code",
            "supplier_name",
            "equipment_id",
            "document_date",
            "invoice_amount",
            "common_business_key",
            "normalized_text"
        ]
    ]
)

hf_dataset

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

sample_tokens = tokenizer(
    hf_dataset[0]["normalized_text"],
    truncation=True,
    padding="max_length",
    max_length=64
)

print("Input IDs length:", len(sample_tokens["input_ids"]))
print("First 20 token IDs:", sample_tokens["input_ids"][:20])

classifier = pipeline(
    "text-classification",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

classification_output = classifier(documents_df["document_text"].head(5).tolist())
classification_output

ner_pipe = pipeline(
    "token-classification",
    model="dslim/bert-base-NER",
    aggregation_strategy="simple"
)

ner_results = ner_pipe(
    "Supplier Bosch reported sensor failure at plant PLT200 on equipment EQP1002 dated 2024-05-16."
)

ner_results

def chunk_text(text, chunk_size=35):
    words = text.split()
    return [" ".join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]

chunk_rows = []

for _, row in documents_df.iterrows():
    chunks = chunk_text(row["normalized_text"], chunk_size=35)
    for idx, chunk in enumerate(chunks, start=1):
        chunk_rows.append({
            "document_id": row["document_id"],
            "chunk_id": f"{row['document_id']}_CHUNK_{idx}",
            "document_type": row["document_type"],
            "company_code": row["company_code"],
            "plant_code": row["plant_code"],
            "supplier_name": row["supplier_name"],
            "equipment_id": row["equipment_id"],
            "document_date": row["document_date"],
            "common_business_key": row["common_business_key"],
            "chunk_text": chunk
        })

chunk_df = pd.DataFrame(chunk_rows)
chunk_df.to_csv(CHUNK_PATH / "chunked_documents.csv", index=False)
chunk_df.head()

chunk_df["embedding_ready_text"] = (
    "DocumentType: " + chunk_df["document_type"] + " | " +
    "CompanyCode: " + chunk_df["company_code"] + " | " +
    "Plant: " + chunk_df["plant_code"] + " | " +
    "Supplier: " + chunk_df["supplier_name"] + " | " +
    "Equipment: " + chunk_df["equipment_id"] + " | " +
    "Date: " + chunk_df["document_date"] + " | " +
    "CommonKey: " + chunk_df["common_business_key"] + " | " +
    "Text: " + chunk_df["chunk_text"]
)

chunk_df.head()

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

embeddings = embedding_model.encode(
    chunk_df["embedding_ready_text"].tolist(),
    show_progress_bar=True
)

print("Embedding shape:", embeddings.shape)

query = "Find supplier related sensor failure documents for plant PLT200 and equipment EQP1002 with finance or issue context"

query_embedding = embedding_model.encode([query])

scores = cosine_similarity(query_embedding, embeddings).flatten()
top_indices = scores.argsort()[-10:][::-1]

search_results = chunk_df.iloc[top_indices].copy()
search_results["similarity_score"] = scores[top_indices]

search_results = search_results[
    [
        "chunk_id",
        "document_id",
        "document_type",
        "company_code",
        "plant_code",
        "supplier_name",
        "equipment_id",
        "document_date",
        "common_business_key",
        "chunk_text",
        "similarity_score"
    ]
]

search_results.to_csv(OUTPUT_PATH / "semantic_search_results.csv", index=False)
search_results.head(10)

model_name = "google-t5/t5-small"

sum_tokenizer = AutoTokenizer.from_pretrained(model_name)
sum_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

sample_context = " ".join(search_results["chunk_text"].head(3).tolist())
sample_context = sample_context[:1200]

prompt = f"summarize: {sample_context}"

inputs = sum_tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

output_ids = sum_model.generate(
    **inputs,
    max_new_tokens=80,
    do_sample=False
)

summary_text = sum_tokenizer.decode(output_ids[0], skip_special_tokens=True)
print(summary_text)

summary_json = {
    "generated_at": datetime.now().isoformat(),
    "document_count": int(len(documents_df)),
    "chunk_count": int(len(chunk_df)),
    "embedding_count": int(len(embeddings)),
    "sample_query": query,
    "top_result_document_id": search_results.iloc[0]["document_id"] if len(search_results) > 0 else None,
    "sample_summary": summary_text
}

with open(OUTPUT_PATH / "project_summary.json", "w") as f:
    json.dump(summary_json, f, indent=2)

print(json.dumps(summary_json, indent=2))

print("Saved files:")
for root, dirs, files in os.walk(BASE_PATH):
    for file in files:
        print(os.path.join(root, file))